### ISSUE TITLE
Vendure integration issue

### ISSUE THREAD

**Issue by Shivam822600** [vendurehq/vendure#1162] opened 2021-10-18 04:13 UTC
Sir i have one issue i want to integrate vendure but he is not understanding how to do so please share any video

**Comment by Shivam822600** [comment] 2021-10-18 10:42
Actually sir i am a beginner for this platform and i am try my best but face many problems and i couldn't integrate vendure to mysql so please help me sir please share any git repository

**Comment by michaelbromley** [comment] 2021-10-18 11:09
Again, you need to be a bit more specific than "i couldn't integrate vendure to mysql" I'm afraid. Things that would help:

- step by step description of what you did
- what the result was vs what you expected to happen
- any error messages (screenshots are fine)

**Comment by Shivam822600** [comment] 2021-10-20 08:01
![Screenshot (135)](https://user-images.githubusercontent.com/85501773/138051242-d8ecbadc-2cb9-46b2-8775-b1bca6679317.png)
sir this is the screenshot of my problem the screenshot show the terminal message when the i am use frontend react native then the backend vendure show his response i  am not able  set any api to vendure  how can set api in vendure

**Comment by michaelbromley** [comment] 2021-10-20 08:47
As it says in the startup message in the terminal, the Vendure ship API is available at `http://localhost:5000/shop-api`. Point your app at that.

I'm going to close this now as it is not a bug or feature request for Vendure. For general help with working with a GraphQL API, try StackOverflow.

**Closed as completed by michaelbromley** 2021-10-20 08:47 UTC
Labels: type: bug 🐛
