### ISSUE TITLE
I can't initialize vendure

### ISSUE THREAD

**Issue by dukeofsoftware** [vendurehq/vendure#2666] opened 2024-02-04 10:02 UTC
Hi! I am trying to initialize the project but I got an error. I have searched on the internet but I didn't find a solution. 
![image](https://github.com/vendure-ecommerce/vendure/assets/89215036/518917f8-2f4d-41a9-89ea-1a636f75fec3)

**Comment by michaelbromley** [comment] 2024-02-05 10:25
Hi,

please provide some more detail - specifically what DB are you attempting to connect to?

**Comment by dukeofsoftware** [comment] 2024-02-05 15:33
Hi, I am trying to connect serverless Neon Postgres database

**Comment by michaelbromley** [comment] 2024-02-06 08:49
OK, it looks like the problem is that during setup, the DB does not get configured to handle an SSL connection.

I recommend this work-around: install with SQLite, and once installed you can then edit the vendure-config.ts file and set the connection settings including the SSL part in the `dbConnectionOptions`.

If you then want to populate your Neon DB with the test data, you can see this guide: https://docs.vendure.io/guides/developer-guide/importing-data/#populating-test-data

**Comment by michaelbromley** [comment] 2024-06-20 09:18
Closing as support for SSL is coming:

- #2905

**Closed as completed by michaelbromley** 2024-06-20 09:18 UTC
